# Generated by Django 4.0.1 on 2022-01-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
