# Generated by Django 4.0.1 on 2022-01-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclass', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
