# Generated by Django 4.0.1 on 2022-01-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclass', '0003_alter_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
