# Generated by Django 3.2.9 on 2021-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclass', '0014_auto_20211225_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
