# Generated by Django 3.2.9 on 2022-01-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclass', '0016_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
